model:
  backbones:
    wideresnet50:
      layers:
        - "layer2"
        - "layer3"
      resize: 256
      image_size: 224
#    wideresnet101:
#      layers:
#        - "layer2"
#        - "layer3"
#      resize: 256
#      image_size: 224
#    resnext101:
#      layers:
#        - "layer2"
#        - "layer3"
#      resize: 256
#      image_size: 224
#    densenet201:
#      layers:
#        - "features.denseblock2"
#        - "features.denseblock3"
#      resize: 256
#      image_size: 224
#    convnext_tiny:
#      layers:
#        - "features.3"
#        - "features.4"
#      resize: 236
#      image_size: 224
#    convnext_small:
#      layers:
#        - "features.3"
#        - "features.4"
#      resize: 230
#      image_size: 224
    convnext_base:
      layers:
        - "features.3"
        - "features.4"
      resize: 232
      image_size: 224
    convnext_large:
      layers:
        - "features.3"
        - "features.4"
      resize: 232
      image_size: 224
  batch_size: 2
  fp16: true

  use_ivf:
    enable: true
    nprobe_scale: 100
  embed_dim: 1024
  patch_size: 3
  gpu: 0
  num_workers: 8
  random_seed: 42

datasets:
  - "bottle"
  - "grid"